/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/worker-configuration.d.ts --include-runtime false` (hash: 79ad5797a5613c8c49ffd608c1c065ea)
interface __BaseEnv_Env {
	RATE_LIMIT: KVNamespace;
	ASSETS: Fetcher;
	SUPABASE_URL: string;
	SUPABASE_KEY: string;
	OPENROUTER_API_KEY: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUPABASE_URL" | "SUPABASE_KEY" | "OPENROUTER_API_KEY">> {}
}
